### ISSUE TITLE
error in koRpus and textstem while using treetagger

### ISSUE THREAD

**Issue by oguzozbay** [unDocUMeantIt/koRpus.lang.en#1]
I installed treetagger but I get an error message in both textstem and roRpus packagesfor below codes:
Would you please help me.

#first example:
Error for koRpus package is as below:

Error in is_grouped_df(tbl) :  "TT.res" adında bir slot yok ("kRp.text" sınıfında bir nesne için)
TRANSLATION in English= 
Error in is_grouped_df(tbl) :  "TT.res" slot missing (for "kRp.text" class object)

#second example
library(textstem)
x <- c(
  'the dirtier dog has eaten the pies',
  'that shameful pooch is tricky and sneaky',
  "He opened and then reopened the food bag",
  'There are skies of blue and red roses too!')
lemma_dictionary2 <- make_lemma_dictionary(x, engine = 'treetagger')

ERROR: Error in dplyr::filter(tagged.results@TT.res[c("token", "lemma")], !lemma %in%  : 
  "TT.res" adında bir slot yok ("kRp.text" sınıfında bir nesne için)

**Comment by unDocUMeantIt** [comment]
it looks like the `textstem` package hasn't been updated yet. the `TT.res` slot was renamed to `tokens` with the release of `koRpus` 0.13-1 a few months ago. you might suggest to its author to use the method `taggedText()` to get the data frame from the tagged object, instead of addressing the slot directly. in this case, you could also use the `[` method introduced in 2017:

```r
tagged.results[c("token", "lemma")]
```

i'll close this issue, as there's nothing i can do about this.

**Comment by oguzozbay** [comment]
Thank you very much for your answer.
I installed older versions of koRpus and koRpus.lang.en.
Now it works.
Best regards

7 Oca 2021 Per 00:18 tarihinde unDocUMeantIt <notifications@github.com>
şunu yazdı:
